#!/bin/sh
# This script reads pywal's generated shell colors and creates an i3 config file
# defining i3 variables for those colors.

WAL_CACHE_DIR="$HOME/.cache/wal"
PYWAL_SHELL_COLORS_FILE="$WAL_CACHE_DIR/colors.sh"
I3_PYWAL_COLORS_OUTPUT_FILE="$WAL_CACHE_DIR/i3_wal_colors.conf" # i3 will include this

# Default fallback colors (e.g., a generic dark theme like Dracula)
# Used if colors.sh is not found (e.g., before pywal runs for the first time)
FALLBACK_BG='#282a36'
FALLBACK_FG='#f8f8f2'
FALLBACK_CURSOR='#f8f8f2'
FALLBACK_C0='#21222c'; FALLBACK_C1='#ff5555'; FALLBACK_C2='#50fa7b'; FALLBACK_C3='#f1fa8c'
FALLBACK_C4='#bd93f9'; FALLBACK_C5='#ff79c6'; FALLBACK_C6='#8be9fd'; FALLBACK_C7='#f8f8f2'
FALLBACK_C8='#6272a4'; FALLBACK_C9='#ff6e6e'; FALLBACK_C10='#69ff94'; FALLBACK_C11='#ffffa5'
FALLBACK_C12='#d6acff'; FALLBACK_C13='#ff92df'; FALLBACK_C14='#a4ffff'; FALLBACK_C15='#ffffff'

if [ -f "$PYWAL_SHELL_COLORS_FILE" ]; then
    # Source the pywal colors to get them as shell variables
    . "$PYWAL_SHELL_COLORS_FILE"

    # Strip single quotes that pywal's colors.sh adds around hex codes
    wal_background=$(echo "$background" | tr -d "'")
    wal_foreground=$(echo "$foreground" | tr -d "'")
    wal_cursor=$(echo "$cursor" | tr -d "'")
    wal_color0=$(echo "$color0" | tr -d "'")
    wal_color1=$(echo "$color1" | tr -d "'")
    wal_color2=$(echo "$color2" | tr -d "'")
    wal_color3=$(echo "$color3" | tr -d "'")
    wal_color4=$(echo "$color4" | tr -d "'")
    wal_color5=$(echo "$color5" | tr -d "'")
    wal_color6=$(echo "$color6" | tr -d "'")
    wal_color7=$(echo "$color7" | tr -d "'")
    wal_color8=$(echo "$color8" | tr -d "'")
    wal_color9=$(echo "$color9" | tr -d "'")
    wal_color10=$(echo "$color10" | tr -d "'")
    wal_color11=$(echo "$color11" | tr -d "'")
    wal_color12=$(echo "$color12" | tr -d "'")
    wal_color13=$(echo "$color13" | tr -d "'")
    wal_color14=$(echo "$color14" | tr -d "'")
    wal_color15=$(echo "$color15" | tr -d "'")
else
    echo "Warning: $PYWAL_SHELL_COLORS_FILE not found. Using fallback colors for i3." >&2
    wal_background=$FALLBACK_BG
    wal_foreground=$FALLBACK_FG
    wal_cursor=$FALLBACK_CURSOR
    wal_color0=$FALLBACK_C0; wal_color1=$FALLBACK_C1; wal_color2=$FALLBACK_C2; wal_color3=$FALLBACK_C3
    wal_color4=$FALLBACK_C4; wal_color5=$FALLBACK_C5; wal_color6=$FALLBACK_C6; wal_color7=$FALLBACK_C7
    wal_color8=$FALLBACK_C8; wal_color9=$FALLBACK_C9; wal_color10=$FALLBACK_C10; wal_color11=$FALLBACK_C11
    wal_color12=$FALLBACK_C12; wal_color13=$FALLBACK_C13; wal_color14=$FALLBACK_C14; wal_color15=$FALLBACK_C15
fi

# Write the i3 'set' commands to the output file
cat > "$I3_PYWAL_COLORS_OUTPUT_FILE" << EOF
# Pywal colors for i3 - auto-generated by generate_i3_wal_colors.sh

set $wal_background ${wal_background}
set $wal_foreground ${wal_foreground}
set $wal_cursor ${wal_cursor}
set $wal_color0 ${wal_color0}
set $wal_color1 ${wal_color1}
set $wal_color2 ${wal_color2}
set $wal_color3 ${wal_color3}
set $wal_color4 ${wal_color4}
set $wal_color5 ${wal_color5}
set $wal_color6 ${wal_color6}
set $wal_color7 ${wal_color7}
set $wal_color8 ${wal_color8}
set $wal_color9 ${wal_color9}
set $wal_color10 ${wal_color10}
set $wal_color11 ${wal_color11}
set $wal_color12 ${wal_color12}
set $wal_color13 ${wal_color13}
set $wal_color14 ${wal_color14}
set $wal_color15 ${wal_color15}
EOF
echo "Generated i3 pywal colors at $I3_PYWAL_COLORS_OUTPUT_FILE"
