#!/bin/bash
if tmux list-sessions -F '#{session_name}:#{session_attached}' | grep -q '^gemini:1$'; then
    tmux detach-client -s gemini
else
    tmux display-popup -w 80% -h 80% -E "tmux new-session -A -s gemini"
fi